name: task_manager_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6 
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


fonts:
      - family: ChesnaGrotesk
        fonts:
          - asset: assets/fonts/Chesna_Grotesk/ChesnaGrotesk-Regular.ttf
            weight: 400
          - asset: assets/fonts/Chesna_Grotesk/ChesnaGrotesk-Medium.ttf
            weight: 500
          - asset: assets/fonts/Chesna_Grotesk/ChesnaGrotesk-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/Chesna_Grotesk/ChesnaGrotesk-Bold.ttf
            weight: 700

